#!/usr/bin/env bash
set -euo pipefail

# ====== CONFIG (edit or export env vars) ======
PGHOST="${PGHOST:-127.0.0.1}"
PGPORT="${PGPORT:-5432}"
PGUSER="${PGUSER:-postgres}"
PGPASSWORD="${PGPASSWORD:-}"

# DBs
SOURCE_DB="${SOURCE_DB:-imos}"         # IMOS DB name (where CONNDESC lives)
TARGET_DB="${TARGET_DB:-imos_helper}"  # helper DB name (where we create conndesc_helper)

export PGPASSWORD

# dblink connection string used FROM target db to source db
DBLINK_CONN="host=${PGHOST} port=${PGPORT} dbname=${SOURCE_DB} user=${PGUSER} password=${PGPASSWORD}"

psql "host=${PGHOST} port=${PGPORT} user=${PGUSER} dbname=${TARGET_DB}" -v ON_ERROR_STOP=1 <<SQL
BEGIN;

-- 0) Enable dblink in imos_helper DB (safe)
CREATE EXTENSION IF NOT EXISTS dblink;

-- 1) Category map table (tag -> canonical category label)
CREATE TABLE IF NOT EXISTS ws_category_map (
  ws_tag   text PRIMARY KEY,
  cat_path text NOT NULL
);

-- 1.1) Seed/refresh category map (idempotent)
INSERT INTO ws_category_map (ws_tag, cat_path) VALUES
  ('#WS_BAT#','Battery'),
  ('#WS_BEQ#','Bequille'),
  ('#WS_BD40#','Bequille porte 40'),
  ('#WS_BD50#','Bequille porte 50'),
  ('#WS_BDBT#','Bequille porte BT'),
  ('#WS_BBTG#','Bequille porte BTG'),
  ('#WS_BDC#','Bequille porte clarit'),
  ('#WS_CAE#','Cartouches encre'),
  ('#WS_CMO#','Charnières Mobilier'),
  ('#WS_CPE#','Cimaise/perlon'),
  ('#WS_CPA#','Cloison'),
  ('#WS_CON#','Consumable'),
  ('#WS_DWI#','Desk window'),
  ('#WS_ECR#','Ecrou'),
  ('#WS_ELE#','Electro'),
  ('#WS_ECO#','Emission de courant'),
  ('#WS_EQU#','Equipement'),
  ('#WS_EQD#','Equipement Porte'),
  ('#WS_EQW#','Equipement Wall'),
  ('#WS_FDR#','Ferme porte'),
  ('#WS_FBTG#','Ferme porte BTG'),
  ('#WS_FES#','Festool'),
  ('#WS_FIX#','Fixation'),
  ('#WS_FMO#','Fixation Mobilier'),
  ('#WS_FOO#','Food'),
  ('#WS_HAN#','Handles'),
  ('#WS_HVE#','Hors vente'),
  ('#WS_MEL#','Material Electrique'),
  ('#WS_OAT#','Outillage Atelier'),
  ('#WS_OCH#','Outillage Chantier'),
  ('#WS_PAP#','Papeterie'),
  ('#WS_PHA#','Pharmacie'),
  ('#WS_PBR#','Protection bruit'),
  ('#WS_PVU#','Protection vue'),
  ('#WS_RD40#','Rosace porte 40'),
  ('#WS_RD50#','Rosace porte 50'),
  ('#WS_RPB#','Rosace porte Beatle'),
  ('#WS_RPBG#','Rosace porte Beatle Glass'),
  ('#WS_RDC#','Rosace porte Clarit'),
  ('#WS_RCA#','Réassort camionnette'),
  ('#WS_SMO#','Serrure Mobilier'),
  ('#WS_D50#','Serrure simple porte 50'),
  ('#WS_SIN#','Sink'),
  ('#WS_SLI#','Slides'),
  ('#WS_STY#','Stylos'),
  ('#WS_TD40#','Tetiere Double porte 40'),
  ('#WS_TD50#','Tetiere Double porte 50'),
  ('#WS_TDDB#','Tetiere Double porte Beatle'),
  ('#WS_TS40#','Tetiere Simple porte 40'),
  ('#WS_TS50#','Tetiere Simple porte 50'),
  ('#WS_TSB#','Tetiere Simple porte BT'),
  ('#WS_TSC#','Tetiere Simple porte clarit'),
  ('#WS_TSBG#','Tetiere porte Simple BTG'),
  ('#WS_TRA#','Trash'),
  ('#WS_VIS#','Visserie'),
  ('#WS_PLI#','plinthe'),
  ('#WS_DD40#','serrure double porte 40'),
  ('#WS_DD50#','serrure double porte 50'),
  ('#WS_DDBG#','serrure double porte Beatle glass'),
  ('#WS_DDBP#','serrure double porte Beatle pleine'),
  ('#WS_D40#','serrure simple porte 40'),
  ('#WS_DBT#','serrure simple porte BT'),
  ('#WS_BTG#','serrure simple porte BTG'),
  ('#WS_DCL#','serrure simple porte clarit')
ON CONFLICT (ws_tag) DO UPDATE
SET cat_path = EXCLUDED.cat_path;

-- 2) Helper table (imos_helper DB is the only place we write)
CREATE TABLE IF NOT EXISTS conndesc_helper (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- snapshot from IMOS (read-only source)
  name        text NOT NULL,
  article_id  text NULL,
  order_id    text NOT NULL,
  text_short  text NOT NULL,
  inorder     text NOT NULL,

  -- derived
  ws_tag      text NULL,
  cat_path    text NULL,

  -- your "source of truth" field for configurator creator (default = conndesc name)
  cfg_name    text NOT NULL,

  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- IMOS already defines uniqueness as (TEXT_SHORT, ORDER_ID, NAME, INORDER)
-- mirror it here so sync is deterministic
CREATE UNIQUE INDEX IF NOT EXISTS conndesc_helper_imos_key_uniq
ON conndesc_helper (text_short, order_id, name, inorder);

-- 3) Sync (UPSERT) from IMOS.CONNDESC into imos_helper.conndesc_helper
WITH src AS (
  SELECT *
  FROM dblink(
    '${DBLINK_CONN}',
    \$\$SELECT
          "NAME",
          "ARTICLE_ID",
          "ORDER_ID",
          "TEXT_SHORT",
          "INORDER"
        FROM public."CONNDESC"
        WHERE "ORDER_ID" ILIKE '%WS%'\$\$
  ) AS t(
    "NAME"      varchar(30),
    "ARTICLE_ID" varchar(50),
    "ORDER_ID"  varchar(50),
    "TEXT_SHORT" varchar(255),
    "INORDER"   varchar(30)
  )
),
enriched AS (
  SELECT
    s."NAME"::text       AS name,
    s."ARTICLE_ID"::text AS article_id,
    s."ORDER_ID"::text   AS order_id,
    s."TEXT_SHORT"::text AS text_short,
    s."INORDER"::text    AS inorder,
    (regexp_match(s."ORDER_ID"::text, '#WS_[A-Z0-9]+#'))[1] AS ws_tag,
    s."NAME"::text       AS cfg_name
  FROM src s
),
final AS (
  SELECT
    e.*,
    m.cat_path
  FROM enriched e
  LEFT JOIN ws_category_map m
    ON m.ws_tag = e.ws_tag
)
INSERT INTO conndesc_helper (
  name, article_id, order_id, text_short, inorder,
  ws_tag, cat_path, cfg_name
)
SELECT
  name, article_id, order_id, text_short, inorder,
  ws_tag, cat_path, cfg_name
FROM final
ON CONFLICT (text_short, order_id, name, inorder)
DO UPDATE SET
  article_id = EXCLUDED.article_id,
  ws_tag     = EXCLUDED.ws_tag,
  cat_path   = EXCLUDED.cat_path,
  cfg_name   = EXCLUDED.cfg_name,
  updated_at = now();

-- 4) Quick report
DO \$\$
DECLARE n int;
BEGIN
  SELECT count(*) INTO n FROM conndesc_helper;
  RAISE NOTICE 'conndesc_helper rows: %', n;
END
\$\$;

COMMIT;
SQL

echo "✅ Sync done: ${TARGET_DB}.conndesc_helper populated from ${SOURCE_DB}.CONNDESC (WS only)."
