import { log } from "./logger";
import { callOdoo } from "./odooRpc";

/**
 * Find reference SO for a project.
 * Prefer sub_so=false, fallback to latest order of that project.
 */
export async function findReferenceSO(session_id, project_id, ctx) {
  const spec = {
    id: {},
    name: {},
    sub_so: {},
    company_id: { fields: { id: {}, display_name: {} } },
    partner_id: { fields: { id: {}, display_name: {} } },
    partner_shipping_id: { fields: { id: {}, display_name: {} } },
    route_id: { fields: { id: {}, display_name: {} } },
    warehouse_id: { fields: { id: {}, display_name: {} } },
    pricelist_id: { fields: { id: {}, display_name: {} } },
    analytic_account_id: { fields: { id: {}, display_name: {} } },
    user_id: { fields: { id: {}, display_name: {} } },
    team_id: { fields: { id: {}, display_name: {} } },
    website_id: { fields: { id: {}, display_name: {} } },
    phase_id: { fields: { id: {}, display_name: {} } },
  };

  const main = await callOdoo(session_id, "sale.order", "web_search_read", [], {
    domain: [
      ["relatedproject_id", "=", project_id],
      ["sub_so", "=", false],
    ],
    order: "id desc",
    limit: 1,
    specification: spec,
    context: ctx,
  });

  const mainRec = main?.records?.[0];
  if (mainRec) return { rec: mainRec, pickedBy: "sub_so=false" };

  const any = await callOdoo(session_id, "sale.order", "web_search_read", [], {
    domain: [["relatedproject_id", "=", project_id]],
    order: "id desc",
    limit: 1,
    specification: spec,
    context: ctx,
  });

  const anyRec = any?.records?.[0];
  if (anyRec) return { rec: anyRec, pickedBy: "fallback:any" };

  return null;
}

/** Extract pickings generated by a sale order. */
export async function fetchPickingsForSaleOrder(session_id, saleOrderId, ctx) {
  try {
    const so = await callOdoo(
      session_id,
      "sale.order",
      "read",
      [[Number(saleOrderId)], ["id", "name", "picking_ids"]],
      { context: ctx }
    );

    const pickingIds = so?.[0]?.picking_ids || [];
    if (!Array.isArray(pickingIds) || pickingIds.length === 0) return [];

    const pickings = await callOdoo(
      session_id,
      "stock.picking",
      "read",
      [
        pickingIds,
        ["id", "name", "state", "scheduled_date", "location_id", "location_dest_id", "picking_type_id"],
      ],
      { context: ctx }
    );

    return pickings || [];
  } catch (e) {
    log("fetchPickingsForSaleOrder failed (non-fatal):", e?.message || e);
    return [];
  }
}
