CREATE TABLE "configurators" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cpid" varchar(100) UNIQUE,
  "description" varchar(500),
  "created_at" timestamp DEFAULT (now()),
  "updated_at" timestamp
);

CREATE TABLE "sections" (
  "label" varchar(100),
  "type" varchar(100),
  "description" varchar(500),
  "termnum" integer,
  "parent_termnum" integer UNIQUE,
  "configurator_id" integer
);

CREATE TABLE "fields" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100),
  "type" "enum(TEXT,INPUT,COMBOBOX)",
  "label" varchar(100),
  "info" varchar(500),
  "required" boolean DEFAULT false,
  "termnum" integer,
  "parent_termnum" integer UNIQUE,
  "configurator_id" integer
);

 "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 CREATE TABLE "impacted_variables" (
  "name" varchar(100),
  "path" varchar(500) DEFAULT null,
  "type" "enum(MAT,SURF,DESCR)",
  "field_id" integer
);

CREATE TABLE "field_descriptions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "lang" varchar(10) DEFAULT 'en',
  "description" varchar(500),
  "field_id" integer
);

CREATE TABLE "input_fields" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "min" float,
  "max" float,
  "type" varchar(50),
  "validation" varchar(255),
  "default_value" varchar(100),
  "field_id" integer UNIQUE,
  "attributes" varchar(500)
);

CREATE TABLE "combobox_fields" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "type" varchar(50),
  "code" varchar(50),
  "content" varchar(500),
  "source" varchar(255),
  "dynamic" boolean DEFAULT false,
  "default_value" varchar(100),
  "field_id" integer UNIQUE
);

CREATE TABLE "dependencies" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "action" "enum(HIDE,CLEAR,FILTER,DISABLE,REQUIRE)",
  "field_id" integer
);

CREATE TABLE "dependency_values" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "result" varchar(255),
  "dependency_id" integer,
  "condition_id" integer UNIQUE
);

CREATE TABLE "conditions" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "comment" varchar(255)
);

CREATE TABLE "comparisons" (
  "condition_id" integer,
  "left_value" varchar(255),
  "right_value" varchar(255),
  "termnum" integer,
  "parent_termnum" integer,
  "comparison_type" varchar(20)
);

CREATE TABLE "operations" (
  "condition_id" integer,
  "termnum" integer,
  "parent_termnum" integer,
  "operation_type" varchar(20)
);



CREATE INDEX ON "configurators" ("cpid");

CREATE INDEX ON "sections" ("configurator_id");

CREATE UNIQUE INDEX ON "sections" ("termnum", "configurator_id");

CREATE INDEX ON "fields" ("configurator_id");

CREATE UNIQUE INDEX ON "fields" ("name", "configurator_id");

CREATE UNIQUE INDEX ON "fields" ("termnum", "configurator_id");

CREATE INDEX ON "impacted_variables" ("field_id");

CREATE UNIQUE INDEX ON "impacted_variables" ("name", "field_id");

CREATE INDEX ON "field_descriptions" ("field_id");

CREATE UNIQUE INDEX ON "field_descriptions" ("lang", "field_id");

CREATE INDEX ON "dependencies" ("field_id");

CREATE INDEX ON "dependency_values" ("dependency_id", "condition_id");

CREATE INDEX ON "comparisons" ("condition_id");

CREATE INDEX ON "operations" ("condition_id");

CREATE UNIQUE INDEX ON "operations" ("condition_id", "termnum");

ALTER TABLE "sections" ADD FOREIGN KEY ("parent_termnum") REFERENCES "sections" ("termnum");

ALTER TABLE "fields" ADD FOREIGN KEY ("parent_termnum") REFERENCES "sections" ("termnum");

ALTER TABLE "fields" ADD FOREIGN KEY ("configurator_id") REFERENCES "configurators" ("id");

ALTER TABLE "sections" ADD FOREIGN KEY ("configurator_id") REFERENCES "fields" ("configurator_id");

ALTER TABLE "impacted_variables" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "field_descriptions" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "input_fields" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "combobox_fields" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "dependencies" ADD FOREIGN KEY ("field_id") REFERENCES "fields" ("id");

ALTER TABLE "dependency_values" ADD FOREIGN KEY ("dependency_id") REFERENCES "dependencies" ("id");

ALTER TABLE "dependency_values" ADD FOREIGN KEY ("condition_id") REFERENCES "conditions" ("id");

ALTER TABLE "comparisons" ADD FOREIGN KEY ("condition_id") REFERENCES "conditions" ("id");

ALTER TABLE "operations" ADD FOREIGN KEY ("condition_id") REFERENCES "comparisons" ("condition_id");

ALTER TABLE "operations" ADD FOREIGN KEY ("termnum") REFERENCES "comparisons" ("parent_termnum");



