export const fallbackProjects = {
    length: 1,
    records: [
      {
        id: 2834,
        display_name: "[233239] SO/TL/2023/1219 - KPMG S.à r.l.",
        partner_id: {
          id: 13369,
          display_name: "KPMG S.à r.l., Frederic Orhant",
        },
        allow_timesheets: true,
        allow_billable: true,
        warning_employee_rate: false,
        sale_order_id: false,
        pricing_type: "task_rate",
        remaining_hours: -2170.6913333333328,
        encode_uom_in_days: false,
        allocated_hours: 0,
        color: 0,
        task_count: 210,
        phase_count: 37,
        closed_task_count: 195,
        open_task_count: 15,
        milestone_count_reached: 0,
        milestone_count: 0,
        allow_milestones: false,
        label_tasks: "Tasks",
        alias_email: false,
        is_favorite: false,
        rating_count: 0,
        rating_avg: 0,
        rating_status: "stage",
        rating_active: false,
        analytic_account_id: {
          id: 10277,
          display_name: "Tecnibo Lux SA [233239] SO/TL/2023/1219 - KPMG S.à r.l.",
        },
        date: "2024-09-30 00:00:00",
        privacy_visibility: "employees",
        last_update_color: 20,
        last_update_status: "on_track",
        tag_ids: [],
        sequence: 10,
        use_documents: true,
        date_start: "2023-09-28",
        total_planned_amount: 0,
        total_budget_progress: 0,
        activity_ids: [],
        activity_exception_decoration: false,
        activity_exception_icon: false,
        activity_state: false,
        activity_summary: false,
        activity_type_icon: false,
        activity_type_id: false,
        user_id: {
          id: 423,
          display_name: "Frederic Moreira",
        },
        display_planning_timesheet_analysis: false,
      },
    ],
    fallback: true
  };
  