export const CATEGORY_ORDER_ID_MAP = {
  "Battery": "#WS_BAT#",
  "Bequille": "#WS_BEQ#",
  "Bequille porte 40": "#WS_BD40#",
  "Bequille porte 50": "#WS_BD50#",
  "Bequille porte BT": "#WS_BDBT#",
  "Bequille porte BTG": "#WS_BBTG#",
  "Bequille porte clarit": "#WS_BDC#",
  "Cartouches encre": "#WS_CAE#",
  "Charnières Mobilier, Charnieres Mobilier": "#WS_CMO#",
  "Cimaise/perlon": "#WS_CPE#",
  "Cloison , Partition": "#WS_CPA#",
  "Consumable": "#WS_CON#",
  "Desk window": "#WS_DWI#",
  "Ecrou": "#WS_ECR#",
  "Electro": "#WS_ELE#",
  "Electro,Four": "#WS_ELE#",
  "Electro,Four,micro": "#WS_ELE#",
  "Electro,Frigo": "#WS_ELE#",
  "Electro,Frigo,Lave-vaisselle,lave vaisselle": "#WS_ELE#",
  "Electro,Frigo,Refrigerateur": "#WS_ELE#",
  "Electro,Lave-vaisselle,Lave vaisselle": "#WS_ELE#",
  "Electro,Lave-vaisselle,lave vaisselle": "#WS_ELE#",
  "Electro,Micro-onde": "#WS_ELE#",
  "Emission de courant": "#WS_ECO#",
  "Equipement": "#WS_EQU#",
  "Equipement Porte": "#WS_EQD#",
  "Equipement Wall": "#WS_EQW#",
  "Ferme porte": "#WS_FDR#",
  "Ferme porte BTG": "#WS_FBTG#",
  "Ferme-portes, Ferme porte, Ferme de porte": "#WS_FDR#",
  "Festool": "#WS_FES#",
  "Fixation": "#WS_FIX#",
  "Fixation Mobilier": "#WS_FMO#",
  "Food": "#WS_FOO#",
  "Handles": "#WS_HAN#",
  "Hors vente": "#WS_HVE#",
  "Material Electrique": "#WS_MEL#",
  "Outillage Atelier": "#WS_OAT#",
  "Outillage Chantier": "#WS_OCH#",
  "Papeterie": "#WS_PAP#",
  "Pharmacie": "#WS_PHA#",
  "Protection bruit": "#WS_PBR#",
  "Protection vue": "#WS_PVU#",
  "Rosace porte 40": "#WS_RD40#",
  "Rosace porte 50": "#WS_RD50#",
  "Rosace porte Beatle": "#WS_RPB#",
  "Rosace porte Beatle Glass": "#WS_RPBG#",
  "Rosace porte Clarit": "#WS_RDC#",
  "Réassort camionnette , Réassort camionnette": "#WS_RCA#",
  "Serrure Mobilier": "#WS_SMO#",
  "Serrure simple porte 50": "#WS_D50#",
  "Sink": "#WS_SIN#",
  "Slides": "#WS_SLI#",
  "Stylos": "#WS_STY#",
  "Tetiere Double porte 40": "#WS_TD40#",
  "Tetiere Double porte 50": "#WS_TD50#",
  "Tetiere Double porte Beatle": "#WS_TDDB#",
  "Tetiere Simple porte 40": "#WS_TS40#",
  "Tetiere Simple porte 50": "#WS_TS50#",
  "Tetiere Simple porte BT , Tetiere Simple porte Beatle": "#WS_TSB#",
  "Tetiere Simple porte clarit": "#WS_TSC#",
  "Tetiere porte Simple BTG , Tetiere porte Simple Beatle Glass": "#WS_TSBG#",
  "Trash,poubelle": "#WS_TRA#",
  "Visserie": "#WS_VIS#",
  "plinthe": "#WS_PLI#",
  "serrure double porte 40": "#WS_DD40#",
  "serrure double porte 50": "#WS_DD50#",
  "serrure double porte Beatle glass": "#WS_DDBG#",
  "serrure double porte Beatle pleine": "#WS_DDBP#",
  "serrure simple porte 40": "#WS_D40#",
  "serrure simple porte BT": "#WS_DBT#",
  "serrure simple porte BTG": "#WS_BTG#",
  "serrure simple porte clarit": "#WS_DCL#",
};
